INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10001, 'Heo', 'Get AWS Certified', CURRENT_DATE(),false);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10002, 'Heo', 'Get DevOps Certified', CURRENT_DATE(),false);
INSERT INTO todo (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE) VALUES (10003, 'Heo', 'Get SpringBoot Certified', CURRENT_DATE(),false);